# Generated by Django 5.1 on 2024-09-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=100)),
                ('or_upload', models.FileField(upload_to='uploads/or/')),
                ('cr_upload', models.FileField(upload_to='uploads/cr/')),
                ('license_upload', models.FileField(upload_to='uploads/license/')),
            ],
        ),
    ]
