# Generated by Django 5.1 on 2024-09-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_studentmasterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmasterlist',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/qr_codes/'),
        ),
    ]
