# Generated by Django 5.1 on 2024-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
    ]
