# Generated by Django 5.1 on 2024-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('violations', models.CharField(max_length=255)),
            ],
        ),
    ]
