# Generated by Django 5.1 on 2024-10-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('qrapp', '0009_studentmasterlist_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('security', 'Security'), ('student', 'Student'), ('head', 'Head of Security')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='qrapp_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='qrapp_user_permissions', to='auth.permission')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
