# Generated by Django 5.1 on 2024-10-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0011_studentmasterlist_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='last_name',
        ),
    ]
