# Generated by Django 5.1 on 2024-10-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0012_remove_studentmasterlist_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmasterlist',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmasterlist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
