# Generated by Django 5.1 on 2024-10-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0014_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
