# Generated by Django 5.1 on 2024-10-27 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0015_violation_first_name_violation_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=10)),
            ],
        ),
    ]
