# Generated by Django 5.1 on 2024-10-27 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0017_alter_logs_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
