# Generated by Django 5.1 on 2024-11-03 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0018_alter_logs_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='violation',
            name='offense_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
