# Generated by Django 5.1 on 2024-11-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0019_violation_date_created_violation_offense_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('or_upload', models.FileField(upload_to='uploads/or/')),
                ('cr_upload', models.FileField(upload_to='uploads/cr/')),
                ('license_upload', models.FileField(upload_to='uploads/license/')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='qrapp.studentmasterlist')),
            ],
        ),
    ]
