# Generated by Django 5.1 on 2024-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0022_alter_vehicle_cr_upload_alter_vehicle_license_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
