# Generated by Django 5.1 on 2024-11-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0024_alter_vehicle_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cr_upload',
        ),
        migrations.RemoveField(
            model_name='student',
            name='license_upload',
        ),
        migrations.RemoveField(
            model_name='student',
            name='or_upload',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='cr_upload',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='license_upload',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='or_upload',
        ),
    ]
