# Generated by Django 5.1 on 2024-11-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0025_remove_student_cr_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('contract', 'Contract of Service')], max_length=10)),
            ],
        ),
    ]
