# Generated by Django 5.1 on 2024-11-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0026_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
