# Generated by Django 5.1 on 2024-11-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0028_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('contract', 'Contract of Service')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
