# Generated by Django 5.1 on 2024-11-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0029_employee_qr_code_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
