# Generated by Django 5.1 on 2024-11-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0031_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('security', 'Security'), ('student', 'Student'), ('head', 'Head of Security'), ('employee', 'Employee')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeVehicle',
            fields=[
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('or_upload', models.FileField(upload_to='uploads/or/')),
                ('cr_upload', models.FileField(upload_to='uploads/cr/')),
                ('license_upload', models.FileField(upload_to='uploads/license/')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='qrapp.employee')),
            ],
        ),
    ]
