# Generated by Django 5.1 on 2024-11-18 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0032_alter_user_user_type_employeevehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('violations', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('offense_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
