# Generated by Django 5.1 on 2024-11-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0033_employeeviolation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeViolation',
        ),
    ]
