# Generated by Django 5.1 on 2024-11-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0036_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plate_number_type',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary Plate'), ('permanent', 'Permanent Plate'), ('improvised', 'Improvised Plate')], max_length=15, null=True),
        ),
    ]
