# Generated by Django 5.1 on 2024-11-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0037_employee_plate_number_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='plate_number_type',
        ),
    ]
