# Generated by Django 5.1 on 2024-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0039_employeevehicle_plate_number_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate_type',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary Plate'), ('permanent', 'Permanent Plate'), ('improvised', 'Improvised Plate')], max_length=15, null=True),
        ),
    ]
