# Generated by Django 5.1 on 2024-12-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0044_employeelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmasterlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
